# Generated by Django 4.1.7 on 2023-03-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Digimon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='test@test.com', max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('img', models.URLField()),
                ('level', models.TextField()),
            ],
        ),
    ]
