version: '3'

services:
  web:
    build: .
    command: gunicorn digimon_api_project.wsgi:application --bind 0.0.0.0:8000 --workers 4
    volumes:
      - .:/code
      - ./static:/usr/src/app/static
    ports:
      - 8000:8000